[window]
padding = { x = 8, y = 8 }

[font]
normal = { family = "monospace", style = "Regular" }
size=7
offset = { x = 0, y = 10 }
glyph_offset = { x = 0, y = 5 }

[cursor]
style = { shape = "Beam", blinking = "On" }
thickness = 0.25

[colors.primary]
background = "#151515"
foreground = "#E8E3E3"

[colors.normal]
black = "#151515"
red = "#B66467"
green = "#8C977D"
yellow = "#D9BC8C"
blue = "#8DA3B9"
magenta = "#A988B0"
cyan = "#8AA6A2"
white = "#E8E3E3"

[colors.bright]
black = "#424242"
red = "#B66467"
green = "#8C977D"
yellow = "#D9BC8C"
blue = "#8DA3B9"
magenta = "#A988B0"
cyan = "#8AA6A2"
white = "#E8E3E3"
